# Generated by Django 3.1.6 on 2021-03-08 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=15, unique=True)),
                ('is_golden_ticket', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_ticket', models.IntegerField(default=0)),
                ('golden_ticket', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('ticket_value', models.IntegerField(default=0)),
                ('item_category', models.CharField(choices=[('1', 'Y+ Package'), ('2', 'Aljay Seeds'), ('3', 'Aljay Chemicals'), ('4', 'Aljay Fertilizer')], max_length=50, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=15)),
                ('standard_ticket', models.IntegerField(default=0)),
                ('golden_ticket', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.coupon')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.farmer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmercoupon.product')),
                ('saleslady', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.saleslady')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.municipality'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.province'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.farmer'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmercoupon.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='saleslady',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.saleslady'),
        ),
    ]
