# Generated by Django 2.2.7 on 2021-03-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.CharField(choices=[('1', 'Y+ Package'), ('2', 'Aljay Biotech'), ('3', 'Premium Grade Fertilizers'), ('4', 'Aljay Hybrid Seed'), ('5', 'Fungicide'), ('6', 'Herbicide'), ('7', 'Insecticide'), ('8', 'Molluscicide'), ('9', 'Foliar Fertilizers')], max_length=50, null=True),
        ),
    ]
