# Generated by Django 3.1.6 on 2021-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0006_auto_20210309_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
