# Generated by Django 3.1.6 on 2021-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0009_auto_20210311_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ticket_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='ticket_value',
            field=models.IntegerField(default=0),
        ),
    ]
