# Generated by Django 3.1.6 on 2021-03-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0012_coupon_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
    ]
