# Generated by Django 2.2.7 on 2021-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0013_remove_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_blo',
            field=models.BooleanField(default=False),
        ),
    ]
