# Generated by Django 3.1.7 on 2021-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0022_remove_farmer_is_blo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
