# Generated by Django 3.1.7 on 2021-03-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0023_auto_20210318_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='province',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.address'),
        ),
    ]
