# Generated by Django 3.1.7 on 2021-03-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0025_auto_20210318_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.farmer'),
        ),
    ]
