# Generated by Django 3.1.7 on 2021-03-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0029_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
    ]
