# Generated by Django 3.1.7 on 2021-03-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0030_remove_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
