# Generated by Django 3.1.7 on 2021-03-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0032_auto_20210319_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='barangay',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='province',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='region',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
