# Generated by Django 3.1.7 on 2021-03-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0037_auto_20210319_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='region',
        ),
    ]
