# Generated by Django 3.1.7 on 2021-03-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_locations', '0001_initial'),
        ('farmercoupon', '0039_auto_20210319_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.city'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.province'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
