# Generated by Django 3.1.7 on 2021-03-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_locations', '0003_auto_20210319_1412'),
        ('farmercoupon', '0040_auto_20210319_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.barangay'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.region'),
        ),
    ]
