# Generated by Django 3.1.7 on 2021-03-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_locations', '0003_auto_20210319_1412'),
        ('farmercoupon', '0041_auto_20210319_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ticket_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.barangay'),
        ),
    ]
