# Generated by Django 3.1.7 on 2021-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0043_auto_20210320_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='access_token',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
