# Generated by Django 2.2.7 on 2021-03-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0044_farmer_province'),
        
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmercoupon.Municipality'),
        ),
        
    ]
