# Generated by Django 3.1.7 on 2021-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0044_farmer_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='globe_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
