# Generated by Django 3.1.7 on 2021-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0046_auto_20210321_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='globe_code',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
