# Generated by Django 3.1.7 on 2021-03-22 02:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0047_auto_20210321_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='land_area',
            field=models.IntegerField(default=0),
        ),
    ]
