# Generated by Django 3.1.7 on 2021-03-22 07:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0049_auto_20210322_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslady',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crops',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'RICE'), (2, 'CORN')], max_length=3, null=True),
        ),
    ]
