# Generated by Django 3.1.7 on 2021-03-23 01:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0050_auto_20210322_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslady',
            name='is_new_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crops',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'RICE'), (2, 'CORN'), (3, 'VEGETABLES'), (4, 'FRUITS'), (5, 'ORNAMENTALS')], max_length=9, null=True),
        ),
    ]
