# Generated by Django 3.1.7 on 2021-03-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0051_auto_20210323_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslady',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
