# Generated by Django 3.1.7 on 2021-03-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0052_auto_20210323_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='last_name',
        ),
    ]
