# Generated by Django 3.1.7 on 2021-03-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0054_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='groups',
        ),
    ]
