# Generated by Django 3.1.7 on 2021-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0055_remove_farmer_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
