# Generated by Django 3.1.7 on 2021-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0057_coupon_generate_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
