# Generated by Django 3.1.7 on 2021-03-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0059_purchases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
