# Generated by Django 3.1.7 on 2021-03-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0060_delete_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleslady',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SalesLady',
        ),
    ]
