# Generated by Django 3.1.7 on 2021-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmercoupon', '0061_auto_20210325_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(choices=[('1', 'Y+ Package'), ('2', 'Aljay Biotech'), ('3', 'Premium Grade Fertilizers'), ('4', 'Aljay Hybrid Seed'), ('5', 'Fungicide'), ('6', 'Herbicide'), ('7', 'Insecticide'), ('8', 'Molluscicide'), ('9', 'Foliar Fertilizers')], max_length=50, null=True)),
                ('price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ticket_value', models.IntegerField(default=0)),
            ],
        ),
    ]
