# Generated by Django 3.1.7 on 2021-03-25 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmercoupon', '0064_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='saleslady',
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
