# Generated by Django 3.1.7 on 2021-03-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0065_auto_20210325_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='is_used',
        ),
    ]
