# Generated by Django 3.1.7 on 2021-03-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmercoupon', '0066_auto_20210328_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
