# Generated by Django 3.1.7 on 2021-03-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('farmercoupon', '0067_auto_20210328_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
        migrations.AddField(
            model_name='purchases',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='saleslady',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.saleslady'),
        ),
    ]
