# Generated by Django 3.1.7 on 2021-03-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('farmercoupon', '0068_auto_20210328_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
    ]
