# Generated by Django 3.1.6 on 2021-02-27 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('is', '0002_auto_20210227_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfarmer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='yfarmer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='yfarmer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='yfarmer',
            name='username',
        ),
        migrations.AddField(
            model_name='yfarmer',
            name='golden_ticket_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yfarmer',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yfarmer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='YFarmerDetails',
        ),
    ]
