# Generated by Django 3.1.6 on 2021-02-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0003_auto_20210227_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YFarmer',
        ),
    ]
