# Generated by Django 2.2.7 on 2021-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0005_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
