# Generated by Django 2.2.7 on 2021-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0006_table_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
