# Generated by Django 3.1.6 on 2021-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0013_product_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
