# Generated by Django 2.2.7 on 2021-03-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0014_purchase_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='farmer',
        ),
    ]
