# Generated by Django 2.2.7 on 2021-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0015_remove_purchase_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
