# Generated by Django 2.2.7 on 2021-03-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0016_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is.Farmer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
