# Generated by Django 2.2.7 on 2021-03-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0018_auto_20210303_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.Farmer'),
        ),
    ]
