# Generated by Django 3.1.6 on 2021-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0022_product_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
