# Generated by Django 2.2.7 on 2021-03-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0024_auto_20210304_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='farmer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.Farmer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='is.Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='saleslady',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.SalesLady'),
        ),
    ]
