# Generated by Django 2.2.7 on 2021-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0026_auto_20210305_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_golden_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
