# Generated by Django 2.2.7 on 2021-03-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0029_auto_20210305_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
    ]
