# Generated by Django 2.2.7 on 2021-03-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0031_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='farmer',
        ),
    ]
