# Generated by Django 2.2.7 on 2021-03-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0032_remove_coupon_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.Farmer'),
        ),
    ]
