# Generated by Django 2.2.7 on 2021-03-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0033_coupon_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_golden_ticket',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='saleslady',
        ),
    ]
