# Generated by Django 2.2.7 on 2021-03-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0036_auto_20210305_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_golden_ticket',
        ),
    ]
