# Generated by Django 2.2.7 on 2021-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0037_remove_coupon_is_golden_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_golden_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
