# Generated by Django 2.2.7 on 2021-03-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0038_coupon_is_golden_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
    ]
