# Generated by Django 2.2.7 on 2021-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0039_remove_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
