# Generated by Django 3.1.6 on 2021-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0040_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
