# Generated by Django 3.1.6 on 2021-03-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0041_coupon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.CharField(choices=[('1', 'Y+ Package'), ('2', 'Aljay Seeds'), ('3', 'Aljay Chemicals'), ('4', 'Aljay Fertilizer')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.coupon')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.farmer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is.product')),
                ('saleslady', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is.saleslady')),
            ],
        ),
    ]
