# Generated by Django 3.1.7 on 2021-03-25 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ph_locations', '0005_auto_20210320_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('standard_ticket', models.IntegerField(default=0)),
                ('golden_ticket', models.IntegerField(default=0)),
                ('is_new_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('globe_code', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('land_area', models.IntegerField(default=0)),
                ('crops', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'RICE'), (2, 'CORN'), (3, 'VEGETABLES'), (4, 'FRUITS'), (5, 'ORNAMENTALS')], max_length=9, null=True)),
                ('standard_ticket', models.IntegerField(default=0)),
                ('golden_ticket', models.IntegerField(default=0)),
                ('is_new_user', models.BooleanField(default=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ph_locations.barangay')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ph_locations.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ph_locations.province')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ph_locations.region')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
