# Generated by Django 3.1.7 on 2021-03-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_locations', '0003_auto_20210319_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ph_locations.region'),
        ),
    ]
